### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by andygruening** [andygruening/SensorFusionVisualization#1]
- [ ] y-Axis drag
- [ ] x-Axis drag
- [ ] central button
- [ ] vertical swipe
- [ ] singelton class that holds the interaction
- [ ] communication class, that passes the data above
- [ ] diconnection status
- [ ] what ip is it connected to
- [ ] log what its connecting to
